### PR TITLE
fix: Fix linux workflow

### PR DESCRIPTION
**Pull request by stefanwimmer128**
Fix linux workflow analogous to windows workflow.

---

See successful run here: https://github.com/stefanwimmer128/noraneko-runtime/actions/runs/11877719961

### CODE REVIEW

**Comment by nyanrus** [comment]
Thank you for your request.

As you can see the README in noraneko repo, now it is using the zip from GH Actions instead of zstd.
Please check the workflow of windows and make the linux workflow to match the windows one.

Thank you for reading. Have a nice day!

**Comment by stefanwimmer128** [comment]
ZIP doesn't support linux file permissions and thus would looses the executable permission on the bineries. https://github.com/actions/upload-artifact#permission-loss

**Comment by nyanrus** [comment]
then please try with just tar, and make match to windows workflow like -dev  and -moz-artifact (-dev is same as the -zstd one, and the -moz-artifact is the artifact for release)

Thank you for reading. Have a nice day!

**Review by nyanrus — APPROVED** [review]
Thank you!
Have a nice day!

**Pull request merged**
