### PR TITLE
Add git patch files

### PR DESCRIPTION
**Pull request by TheChilledBuffalo**

### CODE REVIEW

**Comment by nyanrus** [comment]
I suggest floorpSplitViewIsEnabled to use dynamic injection
you can use the injection with style of non-overriding
move floorpSplitViewIsEnabled to local function and make injection like
```ts
if (remoteTab) {
  browser.renderLayers = true;
  remoteTab.priorityHint = true;
}
```
to 
```ts
const _floorptmp_browser_renderLayer = browser.renderLayers;
const _floorptmp_remoteTab_priorityHint = remoteTab.priorityHint;
if (remoteTab) {
  browser.renderLayers = true;
  remoteTab.priorityHint = true;
}
if (floorpSplitViewIsEnabled()) {
  browser.renderLayers = _floorptmp_browser_renderLayer;
  remoteTab.priorityHint = _floorptmp_remoteTab_priorityHint;
}
```

**Comment by TheChilledBuffalo** [comment]
> so the c++ replacement will removed when I run pull upstream

oh.... but is it possible to use dynamic injection for c++ code?

> I suggest floorpSplitViewIsEnabled to use dynamic injection

Ok, so I should remove the changes here and add injections through my other PR in noraneko, right?

**Comment by nyanrus** [comment]
> Ok, so I should remove the changes here and add injections through my other PR in noraneko, right?
yes
> oh.... but is it possible to use dynamic injection for c++ code?
may the way be better bringing the pull upstream from Floorp

**Comment by nyanrus** [comment]
ah
the injecting can be more simple that the replacing is just string injecting so
```
if (remoteTab) {
  browser.renderLayers = true;
  remoteTab.priorityHint = true;
}
```
to
```
if (!floorpSplitViewIsEnabled()){
if (remoteTab) {
  browser.renderLayers = true;
  remoteTab.priorityHint = true;
}
}
```
maybe this is better

**Comment by TheChilledBuffalo** [comment]
https://stackoverflow.com/a/77145024/15475209

https://stackoverflow.com/a/4832785/15475209

These two stackoverflow comments are important

**Pull request merged**
